services:
  python:
    container_name: etl_python
    build:
      context: ..
      dockerfile: docker/dockerfile
    volumes:
      - ..:/app
    working_dir: /app
    ports:
      - "8888:8888"
    depends_on:
      - mysql
      - postgre
    networks:
      - etl_network
    
  mysql:
    container_name: mysql_db
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: medical_appointments
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - etl_network
  postgre:
    container_name: postgre_db
    image: postgres:15
    environment:
      POSTGRES_DB: appointment_analysis
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - etl_network

networks:
  etl_network:
volumes:
  mysql_data:  
  pgdata:

